### ISSUE TITLE
App doesn't load and dependancies issue

### ISSUE THREAD

**Issue by 0110000101100111** [nuragic/marionette-bootstrap#3]
This looks really nice. The architecture and the module loading especially... although I can't seem to get the app to load. API is fine and npm install is fine; bower does prompt for some resolutions:

```
Unable to find a suitable version for underscore, please choose one by typing one of the numbers below:
    1) underscore#1.4.4 - 1.6.0 which resolved to 1.6.0 and is required by marionette#2.0.3
    2) underscore#>=1.7.0 which resolved to 1.8.3 and is required by backbone#1.2.3
    3) underscore#>=1.5.0 which resolved to 1.8.3 and is required by backbone#1.1.2
    4) underscore#>=1.4.0 <=1.8.3 which resolved to 1.8.3 and is required by backbone.babysitter#0.1.12
```

but trying all possibilities still results in require errors in the browser, as shown below. Any idea what could be wrong? Everything _appears_ to be setup right AFIACT. 😕 

```
require.js:900 TypeError: Cannot read property 'vent' of undefined
    at http://localhost:3000/js/libs/marionette/lib/backbone.marionette.js:466:19
    at arrayEach (http://localhost:3000/js/libs/lodash/lodash.js:451:11)
    at Function.forEach (http://localhost:3000/js/libs/lodash/lodash.js:8634:14)
    at http://localhost:3000/js/libs/marionette/lib/backbone.marionette.js:465:15
    at arrayEach (http://localhost:3000/js/libs/lodash/lodash.js:451:11)
    at Function.forEach (http://localhost:3000/js/libs/lodash/lodash.js:8634:14)
    at Radio._proxyMethods (http://localhost:3000/js/libs/marionette/lib/backbone.marionette.js:464:13)
    at new Radio (http://localhost:3000/js/libs/marionette/lib/backbone.marionette.js:446:14)
    at http://localhost:3000/js/libs/marionette/lib/backbone.marionette.js:483:14
    at http://localhost:3000/js/libs/marionette/lib/backbone.marionette.js:484:6check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783callGetModule @ require.js:1204completeLoad @ require.js:1583onScriptLoad @ require.js:1711
require.js:900 TypeError: Cannot read property 'Region' of undefined
    at http://localhost:3000/js/src/app/views/commons/ModalRegion.js:8:20
    at Object.execCb (http://localhost:3000/js/libs/requirejs/require.js:1690:33)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:865:51)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
    at http://localhost:3000/js/libs/requirejs/require.js:131:23
    at http://localhost:3000/js/libs/requirejs/require.js:1190:21
    at each (http://localhost:3000/js/libs/requirejs/require.js:56:31)
    at Object.emit (http://localhost:3000/js/libs/requirejs/require.js:1189:17)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:940:30)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783callGetModule @ require.js:1204completeLoad @ require.js:1583onScriptLoad @ require.js:1711
require.js:900 TypeError: Cannot read property 'AppRouter' of undefined
    at http://localhost:3000/js/src/app/AppRouter.js:17:20
    at Object.execCb (http://localhost:3000/js/libs/requirejs/require.js:1690:33)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:865:51)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
    at http://localhost:3000/js/libs/requirejs/require.js:131:23
    at http://localhost:3000/js/libs/requirejs/require.js:1190:21
    at each (http://localhost:3000/js/libs/requirejs/require.js:56:31)
    at Object.emit (http://localhost:3000/js/libs/requirejs/require.js:1189:17)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:940:30)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783callGetModule @ require.js:1204completeLoad @ require.js:1583onScriptLoad @ require.js:1711
require.js:900 TypeError: Cannot read property 'ItemView' of undefined
    at http://localhost:3000/js/src/app/views/HomeView.js:8:20
    at Object.execCb (http://localhost:3000/js/libs/requirejs/require.js:1690:33)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:865:51)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
    at http://localhost:3000/js/libs/requirejs/require.js:131:23
    at http://localhost:3000/js/libs/requirejs/require.js:1190:21
    at each (http://localhost:3000/js/libs/requirejs/require.js:56:31)
    at Object.emit (http://localhost:3000/js/libs/requirejs/require.js:1189:17)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:940:30)
    at Object.enable (http://localhost:3000/js/libs/requirejs/require.js:1177:22)check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:983(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:1015(anonymous function) @ require.js:131xhr.onreadystatechange @ loader.js:78
require.js:900 TypeError: Cannot read property 'LayoutView' of undefined
    at http://localhost:3000/js/src/app/AppLayout.js:8:20
    at Object.execCb (http://localhost:3000/js/libs/requirejs/require.js:1690:33)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:865:51)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
    at http://localhost:3000/js/libs/requirejs/require.js:131:23
    at http://localhost:3000/js/libs/requirejs/require.js:1190:21
    at each (http://localhost:3000/js/libs/requirejs/require.js:56:31)
    at Object.emit (http://localhost:3000/js/libs/requirejs/require.js:1189:17)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:940:30)
    at Object.enable (http://localhost:3000/js/libs/requirejs/require.js:1177:22)check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:983(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:1015(anonymous function) @ require.js:131xhr.onreadystatechange @ loader.js:78
require.js:900 TypeError: Cannot read property 'Controller' of undefined
    at http://localhost:3000/js/src/app/AppController.js:13:20
    at Object.execCb (http://localhost:3000/js/libs/requirejs/require.js:1690:33)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:865:51)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
    at http://localhost:3000/js/libs/requirejs/require.js:131:23
    at http://localhost:3000/js/libs/requirejs/require.js:1190:21
    at each (http://localhost:3000/js/libs/requirejs/require.js:56:31)
    at Object.emit (http://localhost:3000/js/libs/requirejs/require.js:1189:17)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:940:30)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:983(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:1015(anonymous function) @ require.js:131xhr.onreadystatechange @ loader.js:78
require.js:900 TypeError: Cannot read property 'Application' of undefined
    at http://localhost:3000/js/src/app/Application.js:32:27
    at Object.execCb (http://localhost:3000/js/libs/requirejs/require.js:1690:33)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:865:51)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
    at http://localhost:3000/js/libs/requirejs/require.js:131:23
    at http://localhost:3000/js/libs/requirejs/require.js:1190:21
    at each (http://localhost:3000/js/libs/requirejs/require.js:56:31)
    at Object.emit (http://localhost:3000/js/libs/requirejs/require.js:1189:17)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:940:30)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)check @ require.js:900(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940(anonymous function) @ require.js:1140(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:983(anonymous function) @ require.js:131(anonymous function) @ require.js:1190each @ require.js:56emit @ require.js:1189check @ require.js:940enable @ require.js:1177init @ require.js:783(anonymous function) @ require.js:1015(anonymous function) @ require.js:131xhr.onreadystatechange @ loader.js:78
require.js:900 TypeError: Cannot read property 'start' of undefined
    at http://localhost:3000/js/src/start.js:8:14
    at Object.execCb (http://localhost:3000/js/libs/requirejs/require.js:1690:33)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:865:51)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
    at http://localhost:3000/js/libs/requirejs/require.js:131:23
    at http://localhost:3000/js/libs/requirejs/require.js:1190:21
    at each (http://localhost:3000/js/libs/requirejs/require.js:56:31)
    at Object.emit (http://localhost:3000/js/libs/requirejs/require.js:1189:17)
    at Object.check (http://localhost:3000/js/libs/requirejs/require.js:940:30)
    at Object.<anonymous> (http://localhost:3000/js/libs/requirejs/require.js:1140:34)
```

**Comment by nuragic** [comment]
Hi, sorry for the delay! Just saw this one for the first time... I'll try to investigate as soon as I can; sorry but I'm quiet busy recently...

But wow, it has been a long time since I run it eheh...  however, thanks so much for reporting this issue, I'm glad you find this project useful! 😄  I think that is a nice architecture as well, on top of a great framework... it just need to be refactored and kept up to date....

_P.D. If you want to make a Pull Request to remove `bower` and just use `npm`, it would be much appreciated!_ 😉

**Comment by rlamtabbet** [comment]
As indicated here: http://www.devsplanet.com/question/35236516.
This issue seems to be caused by the use of lodash 4.x which breaks Marionette. 
Lodash is installed as a dependency of "lodash-template-loader": "0.1.7". 
Unfortunately lodash-template-loader causes bower to install the latest version of lodash.
A quick fix would be to downgrade lodash to version #3.10.1
  - bower uninstall lodash
  - bower install lodash#3.10.1
